[package]
name = "utreexo-rs"
version = "0.1.0"
authors = ["Evgenii P. <eupn@protonmail.com>"]
edition = "2018"
description = "A dynamic hash-based accumulator optimized for the Bitcoin UTXO set"

[dependencies]
